# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active_record_cache 1.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "active_record_cache"
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Brian Durand"]
  s.date = "2015-03-10"
  s.description = "This gem adds a caching layer to ActiveRecord models when finding them by a numeric primary key."
  s.email = ["mdobrota@tribune.com", "ddpr@tribune.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "License.txt",
    "Rakefile",
    "lib/active_record_cache.rb",
    "lib/active_record_cache/defaults_handler.rb",
    "lib/active_record_cache/record_cache.rb",
    "lib/active_record_cache/relation_extension.rb",
    "spec/active_record_cache_spec.rb",
    "spec/defaults_handler_spec.rb",
    "spec/record_cache_spec.rb",
    "spec/relation_extension_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.rdoc_options = ["--line-numbers", "--inline-source", "--main", "README.rdoc"]
  s.rubygems_version = "2.2.2"
  s.summary = "This gem adds a caching layer to ActiveRecord models when finding them by a numeric primary key."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.5"])
      s.add_runtime_dependency(%q<sort_by_field>, ["~> 1.0.1"])
      s.add_development_dependency(%q<rspec>, ["< 3.0", ">= 2.0.0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
    else
      s.add_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.5"])
      s.add_dependency(%q<sort_by_field>, ["~> 1.0.1"])
      s.add_dependency(%q<rspec>, ["< 3.0", ">= 2.0.0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    end
  else
    s.add_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.5"])
    s.add_dependency(%q<sort_by_field>, ["~> 1.0.1"])
    s.add_dependency(%q<rspec>, ["< 3.0", ">= 2.0.0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
  end
end

